// Code generated by entc, DO NOT EDIT.

package video

import (
	"time"
)

const (
	// Label holds the string label denoting the video type in the database.
	Label = "video"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldImgurl holds the string denoting the imgurl field in the database.
	FieldImgurl = "imgurl"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"

	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"

	// Table holds the table name of the video in the database.
	Table = "videos"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "videos"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_id"
)

// Columns holds all SQL columns for video fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDescription,
	FieldURL,
	FieldImgurl,
	FieldTimestamp,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Video type.
var ForeignKeys = []string{
	"user_id",
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// ImgurlValidator is a validator for the "imgurl" field. It is called by the builders before save.
	ImgurlValidator func(string) error
	// DefaultTimestamp holds the default value on creation for the timestamp field.
	DefaultTimestamp func() time.Time
)
