/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntUserEdges,
    EntUserEdgesFromJSON,
    EntUserEdgesFromJSONTyped,
    EntUserEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUser
 */
export interface EntUser {
    /**
     * Birthdate holds the value of the "birthdate" field.
     * @type {string}
     * @memberof EntUser
     */
    birthdate?: string;
    /**
     * 
     * @type {EntUserEdges}
     * @memberof EntUser
     */
    edges?: EntUserEdges;
    /**
     * Email holds the value of the "email" field.
     * @type {string}
     * @memberof EntUser
     */
    email?: string;
    /**
     * Fname holds the value of the "fname" field.
     * @type {string}
     * @memberof EntUser
     */
    fname?: string;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntUser
     */
    id?: number;
    /**
     * Password holds the value of the "password" field.
     * @type {string}
     * @memberof EntUser
     */
    password?: string;
    /**
     * Sname holds the value of the "sname" field.
     * @type {string}
     * @memberof EntUser
     */
    sname?: string;
    /**
     * Tel holds the value of the "tel" field.
     * @type {string}
     * @memberof EntUser
     */
    tel?: string;
}

export function EntUserFromJSON(json: any): EntUser {
    return EntUserFromJSONTyped(json, false);
}

export function EntUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'birthdate': !exists(json, 'birthdate') ? undefined : json['birthdate'],
        'edges': !exists(json, 'edges') ? undefined : EntUserEdgesFromJSON(json['edges']),
        'email': !exists(json, 'email') ? undefined : json['email'],
        'fname': !exists(json, 'fname') ? undefined : json['fname'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'sname': !exists(json, 'sname') ? undefined : json['sname'],
        'tel': !exists(json, 'tel') ? undefined : json['tel'],
    };
}

export function EntUserToJSON(value?: EntUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'birthdate': value.birthdate,
        'edges': EntUserEdgesToJSON(value.edges),
        'email': value.email,
        'fname': value.fname,
        'id': value.id,
        'password': value.password,
        'sname': value.sname,
        'tel': value.tel,
    };
}


